<?php

use Illuminate\Database\Seeder;

class SubdistrictTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subdistricts')->insert([
            ['id' => 1, 'name' => 'Phường Phúc Xá', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 4, 'name' => 'Phường Trúc Bạch', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 6, 'name' => 'Phường Vĩnh Phúc', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 7, 'name' => 'Phường Cống Vị', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 8, 'name' => 'Phường Liễu Giai', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 10, 'name' => 'Phường Nguyễn Trung Trực', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 13, 'name' => 'Phường Quán Thánh', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 16, 'name' => 'Phường Ngọc Hà', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 19, 'name' => 'Phường Điện Biên', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 22, 'name' => 'Phường Đội Cấn', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 25, 'name' => 'Phường Ngọc Khánh', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 28, 'name' => 'Phường Kim Mã', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 31, 'name' => 'Phường Giảng Võ', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 34, 'name' => 'Phường Thành Công', 'type' =>'Phường', 'district_id' => 1],
            ['id' => 37, 'name' => 'Phường Phúc Tân', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 40, 'name' => 'Phường Đồng Xuân', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 43, 'name' => 'Phường Hàng Mã', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 46, 'name' => 'Phường Hàng Buồm', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 49, 'name' => 'Phường Hàng Đào', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 52, 'name' => 'Phường Hàng Bồ', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 55, 'name' => 'Phường Cửa Đông', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 58, 'name' => 'Phường Lý Thái Tổ', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 61, 'name' => 'Phường Hàng Bạc', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 64, 'name' => 'Phường Hàng Gai', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 67, 'name' => 'Phường Chương Dương Độ', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 70, 'name' => 'Phường Hàng Trống', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 73, 'name' => 'Phường Cửa Nam', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 76, 'name' => 'Phường Hàng Bông', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 79, 'name' => 'Phường Tràng Tiền', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 82, 'name' => 'Phường Trần Hưng Đạo', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 85, 'name' => 'Phường Phan Chu Trinh', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 88, 'name' => 'Phường Hàng Bài', 'type' =>'Phường', 'district_id' => 2],
            ['id' => 91, 'name' => 'Phường Phú Thượng', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 94, 'name' => 'Phường Nhật Tân', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 97, 'name' => 'Phường Tứ Liên', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 100, 'name' => 'Phường Quảng An', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 103, 'name' => 'Phường Xuân La', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 106, 'name' => 'Phường Yên Phụ', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 109, 'name' => 'Phường Bưởi', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 112, 'name' => 'Phường Thụy Khuê', 'type' =>'Phường', 'district_id' => 3],
            ['id' => 115, 'name' => 'Phường Thượng Thanh', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 118, 'name' => 'Phường Ngọc Thụy', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 121, 'name' => 'Phường Giang Biên', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 124, 'name' => 'Phường Đức Giang', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 127, 'name' => 'Phường Việt Hưng', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 130, 'name' => 'Phường Gia Thụy', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 133, 'name' => 'Phường Ngọc Lâm', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 136, 'name' => 'Phường Phúc Lợi', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 139, 'name' => 'Phường Bồ Đề', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 142, 'name' => 'Phường Sài Đồng', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 145, 'name' => 'Phường Long Biên', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 148, 'name' => 'Phường Thạch Bàn', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 151, 'name' => 'Phường Phúc Đồng', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 154, 'name' => 'Phường Cự Khối', 'type' =>'Phường', 'district_id' => 4],
            ['id' => 157, 'name' => 'Phường Nghĩa Đô', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 160, 'name' => 'Phường Nghĩa Tân', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 163, 'name' => 'Phường Mai Dịch', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 166, 'name' => 'Phường Dịch Vọng', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 167, 'name' => 'Phường Dịch Vọng Hậu', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 169, 'name' => 'Phường Quan Hoa', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 172, 'name' => 'Phường Yên Hoà', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 175, 'name' => 'Phường Trung Hoà', 'type' =>'Phường', 'district_id' => 5],
            ['id' => 178, 'name' => 'Phường Cát Linh', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 181, 'name' => 'Phường Văn Miếu', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 184, 'name' => 'Phường Quốc Tử Giám', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 187, 'name' => 'Phường Láng Thượng', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 190, 'name' => 'Phường Ô Chợ Dừa', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 193, 'name' => 'Phường Văn Chương', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 196, 'name' => 'Phường Hàng Bột', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 199, 'name' => 'Phường Láng Hạ', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 202, 'name' => 'Phường Khâm Thiên', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 205, 'name' => 'Phường Thổ Quan', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 208, 'name' => 'Phường Nam Đồng', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 211, 'name' => 'Phường Trung Phụng', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 214, 'name' => 'Phường Quang Trung', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 217, 'name' => 'Phường Trung Liệt', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 220, 'name' => 'Phường Phương Liên', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 223, 'name' => 'Phường Thịnh Quang', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 226, 'name' => 'Phường Trung Tự', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 229, 'name' => 'Phường Kim Liên', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 232, 'name' => 'Phường Phương Mai', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 235, 'name' => 'Phường Ngã Tư Sở', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 238, 'name' => 'Phường Khương Thượng', 'type' =>'Phường', 'district_id' => 6],
            ['id' => 241, 'name' => 'Phường Nguyễn Du', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 244, 'name' => 'Phường Bạch Đằng', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 247, 'name' => 'Phường Phạm Đình Hổ', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 250, 'name' => 'Phường Bùi Thị Xuân', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 253, 'name' => 'Phường Ngô Thì Nhậm', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 256, 'name' => 'Phường Lê Đại Hành', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 259, 'name' => 'Phường Đồng Nhân', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 262, 'name' => 'Phường Phố Huế', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 265, 'name' => 'Phường Đống Mác', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 268, 'name' => 'Phường Thanh Lương', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 271, 'name' => 'Phường Thanh Nhàn', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 274, 'name' => 'Phường Cầu Dền', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 277, 'name' => 'Phường Bách Khoa', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 280, 'name' => 'Phường Đồng Tâm', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 283, 'name' => 'Phường Vĩnh Tuy', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 286, 'name' => 'Phường Bạch Mai', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 289, 'name' => 'Phường Quỳnh Mai', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 292, 'name' => 'Phường Quỳnh Lôi', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 295, 'name' => 'Phường Minh Khai', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 298, 'name' => 'Phường Trương Định', 'type' =>'Phường', 'district_id' => 7],
            ['id' => 301, 'name' => 'Phường Thanh Trì', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 304, 'name' => 'Phường Vĩnh Hưng', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 307, 'name' => 'Phường Định Công', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 310, 'name' => 'Phường Mai Động', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 313, 'name' => 'Phường Tương Mai', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 316, 'name' => 'Phường Đại Kim', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 319, 'name' => 'Phường Tân Mai', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 322, 'name' => 'Phường Hoàng Văn Thụ', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 325, 'name' => 'Phường Giáp Bát', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 328, 'name' => 'Phường Lĩnh Nam', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 331, 'name' => 'Phường Thịnh Liệt', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 334, 'name' => 'Phường Trần Phú', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 337, 'name' => 'Phường Hoàng Liệt', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 340, 'name' => 'Phường Yên Sở', 'type' =>'Phường', 'district_id' => 8],
            ['id' => 343, 'name' => 'Phường Nhân Chính', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 346, 'name' => 'Phường Thượng Đình', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 349, 'name' => 'Phường Khương Trung', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 352, 'name' => 'Phường Khương Mai', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 355, 'name' => 'Phường Thanh Xuân Trung', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 358, 'name' => 'Phường Phương Liệt', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 361, 'name' => 'Phường Hạ Đình', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 364, 'name' => 'Phường Khương Đình', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 367, 'name' => 'Phường Thanh Xuân Bắc', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 370, 'name' => 'Phường Thanh Xuân Nam', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 373, 'name' => 'Phường Kim Giang', 'type' =>'Phường', 'district_id' => 9],
            ['id' => 376, 'name' => 'Thị trấn Sóc Sơn', 'type' => 'Thị trấn', 'district_id' => 16],
            ['id' => 379, 'name' => 'Xã Bắc Sơn', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 382, 'name' => 'Xã Minh Trí', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 385, 'name' => 'Xã Hồng Kỳ', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 388, 'name' => 'Xã Nam Sơn', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 391, 'name' => 'Xã Trung Giã', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 394, 'name' => 'Xã Tân Hưng', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 397, 'name' => 'Xã Minh Phú', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 400, 'name' => 'Xã Phù Linh', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 403, 'name' => 'Xã Bắc Phú', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 406, 'name' => 'Xã Tân Minh', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 409, 'name' => 'Xã Quang Tiến', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 412, 'name' => 'Xã Hiền Ninh', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 415, 'name' => 'Xã Tân Dân', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 418, 'name' => 'Xã Tiên Dược', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 421, 'name' => 'Xã Việt Long', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 424, 'name' => 'Xã Xuân Giang', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 427, 'name' => 'Xã Mai Đình', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 430, 'name' => 'Xã Đức Hoà', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 433, 'name' => 'Xã Thanh Xuân', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 436, 'name' => 'Xã Đông Xuân', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 439, 'name' => 'Xã Kim Lũ', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 442, 'name' => 'Xã Phú Cường', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 445, 'name' => 'Xã Phú Minh', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 448, 'name' => 'Xã Phù Lỗ', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 451, 'name' => 'Xã Xuân Thu', 'type' => 'Xã', 'district_id' => 16],
            ['id' => 454, 'name' => 'Thị trấn Đông Anh', 'type' => 'Thị trấn', 'district_id' => 17],
            ['id' => 457, 'name' => 'Xã Xuân Nộn', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 460, 'name' => 'Xã Thuỵ Lâm', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 463, 'name' => 'Xã Bắc Hồng', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 466, 'name' => 'Xã Nguyên Khê', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 469, 'name' => 'Xã Nam Hồng', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 472, 'name' => 'Xã Tiên Dương', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 475, 'name' => 'Xã Vân Hà', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 478, 'name' => 'Xã Uy Nỗ', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 481, 'name' => 'Xã Vân Nội', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 484, 'name' => 'Xã Liên Hà', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 487, 'name' => 'Xã Việt Hùng', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 490, 'name' => 'Xã Kim Nỗ', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 493, 'name' => 'Xã Kim Chung', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 496, 'name' => 'Xã Dục Tú', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 499, 'name' => 'Xã Đại Mạch', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 502, 'name' => 'Xã Vĩnh Ngọc', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 505, 'name' => 'Xã Cổ Loa', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 508, 'name' => 'Xã Hải Bối', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 511, 'name' => 'Xã Xuân Canh', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 514, 'name' => 'Xã Võng La', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 517, 'name' => 'Xã Tầm Xá', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 520, 'name' => 'Xã Mai Lâm', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 523, 'name' => 'Xã Đông Hội', 'type' => 'Xã', 'district_id' => 17],
            ['id' => 526, 'name' => 'Thị trấn Yên Viên', 'type' => 'Thị trấn', 'district_id' => 18],
            ['id' => 529, 'name' => 'Xã Yên Thường', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 532, 'name' => 'Xã Yên Viên', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 535, 'name' => 'Xã Ninh Hiệp', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 538, 'name' => 'Xã Đình Xuyên', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 541, 'name' => 'Xã Dương Hà', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 544, 'name' => 'Xã Phù Đổng', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 547, 'name' => 'Xã Trung Mầu', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 550, 'name' => 'Xã Lệ Chi', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 553, 'name' => 'Xã Cổ Bi', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 556, 'name' => 'Xã Đặng Xá', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 559, 'name' => 'Xã Phú Thị', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 562, 'name' => 'Xã Kim Sơn', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 565, 'name' => 'Thị trấn Trâu Quỳ', 'type' => 'Thị trấn', 'district_id' => 18],
            ['id' => 568, 'name' => 'Xã Dương Quang', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 571, 'name' => 'Xã Dương Xá', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 574, 'name' => 'Xã Đông Dư', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 577, 'name' => 'Xã Đa Tốn', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 580, 'name' => 'Xã Kiêu Kỵ', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 583, 'name' => 'Xã Bát Tràng', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 586, 'name' => 'Xã Kim Lan', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 589, 'name' => 'Xã Văn Đức', 'type' => 'Xã', 'district_id' => 18],
            ['id' => 592, 'name' => 'Phường Cầu Diễn', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 595, 'name' => 'Phường Thượng Cát', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 598, 'name' => 'Phường Liên Mạc', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 601, 'name' => 'Phường Đông Ngạc', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 602, 'name' => 'Phường Đức Thắng', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 604, 'name' => 'Phường Thụy Phương', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 607, 'name' => 'Phường Tây Tựu', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 610, 'name' => 'Phường Xuân Đỉnh', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 611, 'name' => 'Phường Xuân Tảo', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 613, 'name' => 'Phường Minh Khai', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 616, 'name' => 'Phường Cổ Nhuế 1', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 617, 'name' => 'Phường Cổ Nhuế 2', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 619, 'name' => 'Phường Phú Diễn', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 620, 'name' => 'Phường Phúc Diễn', 'type' =>'Phường', 'district_id' => 21],
            ['id' => 622, 'name' => 'Phường Xuân Phương', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 623, 'name' => 'Phường Phương Canh', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 625, 'name' => 'Phường Mỹ Đình 1', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 626, 'name' => 'Phường Mỹ Đình 2', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 628, 'name' => 'Phường Tây Mỗ', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 631, 'name' => 'Phường Mễ Trì', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 632, 'name' => 'Phường Phú Đô', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 634, 'name' => 'Phường Đại Mỗ', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 637, 'name' => 'Phường Trung Văn', 'type' =>'Phường', 'district_id' => 19],
            ['id' => 640, 'name' => 'Thị trấn Văn Điển', 'type' => 'Thị trấn', 'district_id' => 20],
            ['id' => 643, 'name' => 'Xã Tân Triều', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 646, 'name' => 'Xã Thanh Liệt', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 649, 'name' => 'Xã Tả Thanh Oai', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 652, 'name' => 'Xã Hữu Hoà', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 655, 'name' => 'Xã Tam Hiệp', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 658, 'name' => 'Xã Tứ Hiệp', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 661, 'name' => 'Xã Yên Mỹ', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 664, 'name' => 'Xã Vĩnh Quỳnh', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 667, 'name' => 'Xã Ngũ Hiệp', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 670, 'name' => 'Xã Duyên Hà', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 673, 'name' => 'Xã Ngọc Hồi', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 676, 'name' => 'Xã Vạn Phúc', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 679, 'name' => 'Xã Đại áng', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 682, 'name' => 'Xã Liên Ninh', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 685, 'name' => 'Xã Đông Mỹ', 'type' => 'Xã', 'district_id' => 20],
            ['id' => 4927, 'name' => 'Xã Yên Trung', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 4930, 'name' => 'Xã Yên Bình', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 4936, 'name' => 'Xã Tiến Xuân', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 4939, 'name' => 'Xã Đông Xuân', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 8973, 'name' => 'Thị trấn Chi Đông', 'type' => 'Thị trấn', 'district_id' => 250],
            ['id' => 8974, 'name' => 'Xã Đại Thịnh', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 8977, 'name' => 'Xã Kim Hoa', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 8980, 'name' => 'Xã Thạch Đà', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 8983, 'name' => 'Xã Tiến Thắng', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 8986, 'name' => 'Xã Tự Lập', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 8989, 'name' => 'Thị trấn Quang Minh', 'type' => 'Thị trấn', 'district_id' => 250],
            ['id' => 8992, 'name' => 'Xã Thanh Lâm', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 8995, 'name' => 'Xã Tam Đồng', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 8998, 'name' => 'Xã Liên Mạc', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9001, 'name' => 'Xã Vạn Yên', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9004, 'name' => 'Xã Chu Phan', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9007, 'name' => 'Xã Tiến Thịnh', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9010, 'name' => 'Xã Mê Linh', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9013, 'name' => 'Xã Văn Khê', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9016, 'name' => 'Xã Hoàng Kim', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9019, 'name' => 'Xã Tiền Phong', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9022, 'name' => 'Xã Tráng Việt', 'type' => 'Xã', 'district_id' => 250],
            ['id' => 9538, 'name' => 'Phường Nguyễn Trãi', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9541, 'name' => 'Phường Mộ Lao', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9542, 'name' => 'Phường Văn Quán', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9544, 'name' => 'Phường Vạn Phúc', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9547, 'name' => 'Phường Yết Kiêu', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9550, 'name' => 'Phường Quang Trung', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9551, 'name' => 'Phường La Khê', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9552, 'name' => 'Phường Phú La', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9553, 'name' => 'Phường Phúc La', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9556, 'name' => 'Phường Hà Cầu', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9562, 'name' => 'Phường Yên Nghĩa', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9565, 'name' => 'Phường Kiến Hưng', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9568, 'name' => 'Phường Phú Lãm', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9571, 'name' => 'Phường Phú Lương', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9574, 'name' => 'Phường Lê Lợi', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9577, 'name' => 'Phường Phú Thịnh', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9580, 'name' => 'Phường Ngô Quyền', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9583, 'name' => 'Phường Quang Trung', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9586, 'name' => 'Phường Sơn Lộc', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9589, 'name' => 'Phường Xuân Khanh', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9592, 'name' => 'Xã Đường Lâm', 'type' => 'Xã', 'district_id' => 269],
            ['id' => 9595, 'name' => 'Phường Viên Sơn', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9598, 'name' => 'Xã Xuân Sơn', 'type' => 'Xã', 'district_id' => 269],
            ['id' => 9601, 'name' => 'Phường Trung Hưng', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9604, 'name' => 'Xã Thanh Mỹ', 'type' => 'Xã', 'district_id' => 269],
            ['id' => 9607, 'name' => 'Phường Trung Sơn Trầm', 'type' =>'Phường', 'district_id' => 269],
            ['id' => 9610, 'name' => 'Xã Kim Sơn', 'type' => 'Xã', 'district_id' => 269],
            ['id' => 9613, 'name' => 'Xã Sơn Đông', 'type' => 'Xã', 'district_id' => 269],
            ['id' => 9616, 'name' => 'Xã Cổ Đông', 'type' => 'Xã', 'district_id' => 269],
            ['id' => 9619, 'name' => 'Thị trấn Tây Đằng', 'type' => 'Thị trấn', 'district_id' => 271],
            ['id' => 9625, 'name' => 'Xã Phú Cường', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9628, 'name' => 'Xã Cổ Đô', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9631, 'name' => 'Xã Tản Hồng', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9634, 'name' => 'Xã Vạn Thắng', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9637, 'name' => 'Xã Châu Sơn', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9640, 'name' => 'Xã Phong Vân', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9643, 'name' => 'Xã Phú Đông', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9646, 'name' => 'Xã Phú Phương', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9649, 'name' => 'Xã Phú Châu', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9652, 'name' => 'Xã Thái Hòa', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9655, 'name' => 'Xã Đồng Thái', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9658, 'name' => 'Xã Phú Sơn', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9661, 'name' => 'Xã Minh Châu', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9664, 'name' => 'Xã Vật Lại', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9667, 'name' => 'Xã Chu Minh', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9670, 'name' => 'Xã Tòng Bạt', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9673, 'name' => 'Xã Cẩm Lĩnh', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9676, 'name' => 'Xã Sơn Đà', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9679, 'name' => 'Xã Đông Quang', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9682, 'name' => 'Xã Tiên Phong', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9685, 'name' => 'Xã Thụy An', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9688, 'name' => 'Xã Cam Thượng', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9691, 'name' => 'Xã Thuần Mỹ', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9694, 'name' => 'Xã Tản Lĩnh', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9697, 'name' => 'Xã Ba Trại', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9700, 'name' => 'Xã Minh Quang', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9703, 'name' => 'Xã Ba Vì', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9706, 'name' => 'Xã Vân Hòa', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9709, 'name' => 'Xã Yên Bài', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9712, 'name' => 'Xã Khánh Thượng', 'type' => 'Xã', 'district_id' => 271],
            ['id' => 9715, 'name' => 'Thị trấn Phúc Thọ', 'type' => 'Thị trấn', 'district_id' => 272],
            ['id' => 9718, 'name' => 'Xã Vân Hà', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9721, 'name' => 'Xã Vân Phúc', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9724, 'name' => 'Xã Vân Nam', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9727, 'name' => 'Xã Xuân Phú', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9730, 'name' => 'Xã Phương Độ', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9733, 'name' => 'Xã Sen Chiểu', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9736, 'name' => 'Xã Cẩm Đình', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9739, 'name' => 'Xã Võng Xuyên', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9742, 'name' => 'Xã Thọ Lộc', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9745, 'name' => 'Xã Long Xuyên', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9748, 'name' => 'Xã Thượng Cốc', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9751, 'name' => 'Xã Hát Môn', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9754, 'name' => 'Xã Tích Giang', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9757, 'name' => 'Xã Thanh Đa', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9760, 'name' => 'Xã Trạch Mỹ Lộc', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9763, 'name' => 'Xã Phúc Hòa', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9766, 'name' => 'Xã Ngọc Tảo', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9769, 'name' => 'Xã Phụng Thượng', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9772, 'name' => 'Xã Tam Thuấn', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9775, 'name' => 'Xã Tam Hiệp', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9778, 'name' => 'Xã Hiệp Thuận', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9781, 'name' => 'Xã Liên Hiệp', 'type' => 'Xã', 'district_id' => 272],
            ['id' => 9784, 'name' => 'Thị trấn Phùng', 'type' => 'Thị trấn', 'district_id' => 273],
            ['id' => 9787, 'name' => 'Xã Trung Châu', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9790, 'name' => 'Xã Thọ An', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9793, 'name' => 'Xã Thọ Xuân', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9796, 'name' => 'Xã Hồng Hà', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9799, 'name' => 'Xã Liên Hồng', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9802, 'name' => 'Xã Liên Hà', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9805, 'name' => 'Xã Hạ Mỗ', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9808, 'name' => 'Xã Liên Trung', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9811, 'name' => 'Xã Phương Đình', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9814, 'name' => 'Xã Thượng Mỗ', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9817, 'name' => 'Xã Tân Hội', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9820, 'name' => 'Xã Tân Lập', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9823, 'name' => 'Xã Đan Phượng', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9826, 'name' => 'Xã Đồng Tháp', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9829, 'name' => 'Xã Song Phượng', 'type' => 'Xã', 'district_id' => 273],
            ['id' => 9832, 'name' => 'Thị trấn Trạm Trôi', 'type' => 'Thị trấn', 'district_id' => 274],
            ['id' => 9835, 'name' => 'Xã Đức Thượng', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9838, 'name' => 'Xã Minh Khai', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9841, 'name' => 'Xã Dương Liễu', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9844, 'name' => 'Xã Di Trạch', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9847, 'name' => 'Xã Đức Giang', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9850, 'name' => 'Xã Cát Quế', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9853, 'name' => 'Xã Kim Chung', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9856, 'name' => 'Xã Yên Sở', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9859, 'name' => 'Xã Sơn Đồng', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9862, 'name' => 'Xã Vân Canh', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9865, 'name' => 'Xã Đắc Sở', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9868, 'name' => 'Xã Lại Yên', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9871, 'name' => 'Xã Tiền Yên', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9874, 'name' => 'Xã Song Phương', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9877, 'name' => 'Xã An Khánh', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9880, 'name' => 'Xã An Thượng', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9883, 'name' => 'Xã Vân Côn', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9886, 'name' => 'Phường Dương Nội', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 9889, 'name' => 'Xã La Phù', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9892, 'name' => 'Xã Đông La', 'type' => 'Xã', 'district_id' => 274],
            ['id' => 9895, 'name' => 'Thị trấn Quốc Oai', 'type' => 'Thị trấn', 'district_id' => 275],
            ['id' => 9898, 'name' => 'Xã Sài Sơn', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9901, 'name' => 'Xã Phượng Cách', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9904, 'name' => 'Xã Yên Sơn', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9907, 'name' => 'Xã Ngọc Liệp', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9910, 'name' => 'Xã Ngọc Mỹ', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9913, 'name' => 'Xã Liệp Tuyết', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9916, 'name' => 'Xã Thạch Thán', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9919, 'name' => 'Xã Đồng Quang', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9922, 'name' => 'Xã Phú Cát', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9925, 'name' => 'Xã Tuyết Nghĩa', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9928, 'name' => 'Xã Nghĩa Hương', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9931, 'name' => 'Xã Cộng Hòa', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9934, 'name' => 'Xã Tân Phú', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9937, 'name' => 'Xã Đại Thành', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9940, 'name' => 'Xã Phú Mãn', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9943, 'name' => 'Xã Cấn Hữu', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9946, 'name' => 'Xã Tân Hòa', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9949, 'name' => 'Xã Hòa Thạch', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9952, 'name' => 'Xã Đông Yên', 'type' => 'Xã', 'district_id' => 275],
            ['id' => 9955, 'name' => 'Thị trấn Liên Quan', 'type' => 'Thị trấn', 'district_id' => 276],
            ['id' => 9958, 'name' => 'Xã Đại Đồng', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9961, 'name' => 'Xã Cẩm Yên', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9964, 'name' => 'Xã Lại Thượng', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9967, 'name' => 'Xã Phú Kim', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9970, 'name' => 'Xã Hương Ngải', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9973, 'name' => 'Xã Canh Nậu', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9976, 'name' => 'Xã Kim Quan', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9979, 'name' => 'Xã Dị Nậu', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9982, 'name' => 'Xã Bình Yên', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9985, 'name' => 'Xã Chàng Sơn', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9988, 'name' => 'Xã Thạch Hoà', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9991, 'name' => 'Xã Cần Kiệm', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9994, 'name' => 'Xã Hữu Bằng', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 9997, 'name' => 'Xã Phùng Xá', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 10000, 'name' => 'Xã Tân Xã', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 10003, 'name' => 'Xã Thạch Xá', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 10006, 'name' => 'Xã Bình Phú', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 10009, 'name' => 'Xã Hạ Bằng', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 10012, 'name' => 'Xã Đồng Trúc', 'type' => 'Xã', 'district_id' => 276],
            ['id' => 10015, 'name' => 'Thị trấn Chúc Sơn', 'type' => 'Thị trấn', 'district_id' => 277],
            ['id' => 10018, 'name' => 'Thị trấn Xuân Mai', 'type' => 'Thị trấn', 'district_id' => 277],
            ['id' => 10021, 'name' => 'Xã Phụng Châu', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10024, 'name' => 'Xã Tiên Phương', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10027, 'name' => 'Xã Đông Sơn', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10030, 'name' => 'Xã Đông Phương Yên', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10033, 'name' => 'Xã Phú Nghĩa', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10039, 'name' => 'Xã Trường Yên', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10042, 'name' => 'Xã Ngọc Hòa', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10045, 'name' => 'Xã Thủy Xuân Tiên', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10048, 'name' => 'Xã Thanh Bình', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10051, 'name' => 'Xã Trung Hòa', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10054, 'name' => 'Xã Đại Yên', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10057, 'name' => 'Xã Thụy Hương', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10060, 'name' => 'Xã Tốt Động', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10063, 'name' => 'Xã Lam Điền', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10066, 'name' => 'Xã Tân Tiến', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10069, 'name' => 'Xã Nam Phương Tiến', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10072, 'name' => 'Xã Hợp Đồng', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10075, 'name' => 'Xã Hoàng Văn Thụ', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10078, 'name' => 'Xã Hoàng Diệu', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10081, 'name' => 'Xã Hữu Văn', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10084, 'name' => 'Xã Quảng Bị', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10087, 'name' => 'Xã Mỹ Lương', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10090, 'name' => 'Xã Thượng Vực', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10093, 'name' => 'Xã Hồng Phong', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10096, 'name' => 'Xã Đồng Phú', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10099, 'name' => 'Xã Trần Phú', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10102, 'name' => 'Xã Văn Võ', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10105, 'name' => 'Xã Đồng Lạc', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10108, 'name' => 'Xã Hòa Chính', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10111, 'name' => 'Xã Phú Nam An', 'type' => 'Xã', 'district_id' => 277],
            ['id' => 10114, 'name' => 'Thị trấn Kim Bài', 'type' => 'Thị trấn', 'district_id' => 278],
            ['id' => 10117, 'name' => 'Phường Đồng Mai', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 10120, 'name' => 'Xã Cự Khê', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10123, 'name' => 'Phường Biên Giang', 'type' =>'Phường', 'district_id' => 268],
            ['id' => 10126, 'name' => 'Xã Bích Hòa', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10129, 'name' => 'Xã Mỹ Hưng', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10132, 'name' => 'Xã Cao Viên', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10135, 'name' => 'Xã Bình Minh', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10138, 'name' => 'Xã Tam Hưng', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10141, 'name' => 'Xã Thanh Cao', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10144, 'name' => 'Xã Thanh Thùy', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10147, 'name' => 'Xã Thanh Mai', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10150, 'name' => 'Xã Thanh Văn', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10153, 'name' => 'Xã Đỗ Động', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10156, 'name' => 'Xã Kim An', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10159, 'name' => 'Xã Kim Thư', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10162, 'name' => 'Xã Phương Trung', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10165, 'name' => 'Xã Tân Ước', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10168, 'name' => 'Xã Dân Hòa', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10171, 'name' => 'Xã Liên Châu', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10174, 'name' => 'Xã Cao Dương', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10177, 'name' => 'Xã Xuân Dương', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10180, 'name' => 'Xã Hồng Dương', 'type' => 'Xã', 'district_id' => 278],
            ['id' => 10183, 'name' => 'Thị trấn Thường Tín', 'type' => 'Thị trấn', 'district_id' => 279],
            ['id' => 10186, 'name' => 'Xã Ninh Sở', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10189, 'name' => 'Xã Nhị Khê', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10192, 'name' => 'Xã Duyên Thái', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10195, 'name' => 'Xã Khánh Hà', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10198, 'name' => 'Xã Hòa Bình', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10201, 'name' => 'Xã Văn Bình', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10204, 'name' => 'Xã Hiền Giang', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10207, 'name' => 'Xã Hồng Vân', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10210, 'name' => 'Xã Vân Tảo', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10213, 'name' => 'Xã Liên Phương', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10216, 'name' => 'Xã Văn Phú', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10219, 'name' => 'Xã Tự Nhiên', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10222, 'name' => 'Xã Tiền Phong', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10225, 'name' => 'Xã Hà Hồi', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10228, 'name' => 'Xã Thư Phú', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10231, 'name' => 'Xã Nguyễn Trãi', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10234, 'name' => 'Xã Quất Động', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10237, 'name' => 'Xã Chương Dương', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10240, 'name' => 'Xã Tân Minh', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10243, 'name' => 'Xã Lê Lợi', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10246, 'name' => 'Xã Thắng Lợi', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10249, 'name' => 'Xã Dũng Tiến', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10252, 'name' => 'Xã Thống Nhất', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10255, 'name' => 'Xã Nghiêm Xuyên', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10258, 'name' => 'Xã Tô Hiệu', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10261, 'name' => 'Xã Văn Tự', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10264, 'name' => 'Xã Vạn Điểm', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10267, 'name' => 'Xã Minh Cường', 'type' => 'Xã', 'district_id' => 279],
            ['id' => 10270, 'name' => 'Thị trấn Phú Minh', 'type' => 'Thị trấn', 'district_id' => 280],
            ['id' => 10273, 'name' => 'Thị trấn Phú Xuyên', 'type' => 'Thị trấn', 'district_id' => 280],
            ['id' => 10276, 'name' => 'Xã Hồng Minh', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10279, 'name' => 'Xã Phượng Dực', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10282, 'name' => 'Xã Văn Nhân', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10285, 'name' => 'Xã Thụy Phú', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10288, 'name' => 'Xã Tri Trung', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10291, 'name' => 'Xã Đại Thắng', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10294, 'name' => 'Xã Phú Túc', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10297, 'name' => 'Xã Văn Hoàng', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10300, 'name' => 'Xã Hồng Thái', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10303, 'name' => 'Xã Hoàng Long', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10306, 'name' => 'Xã Quang Trung', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10309, 'name' => 'Xã Nam Phong', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10312, 'name' => 'Xã Nam Triều', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10315, 'name' => 'Xã Tân Dân', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10318, 'name' => 'Xã Sơn Hà', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10321, 'name' => 'Xã Chuyên Mỹ', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10324, 'name' => 'Xã Khai Thái', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10327, 'name' => 'Xã Phúc Tiến', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10330, 'name' => 'Xã Vân Từ', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10333, 'name' => 'Xã Tri Thủy', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10336, 'name' => 'Xã Đại Xuyên', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10339, 'name' => 'Xã Phú Yên', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10342, 'name' => 'Xã Bạch Hạ', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10345, 'name' => 'Xã Quang Lãng', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10348, 'name' => 'Xã Châu Can', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10351, 'name' => 'Xã Minh Tân', 'type' => 'Xã', 'district_id' => 280],
            ['id' => 10354, 'name' => 'Thị trấn Vân Đình', 'type' => 'Thị trấn', 'district_id' => 281],
            ['id' => 10357, 'name' => 'Xã Viên An', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10360, 'name' => 'Xã Viên Nội', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10363, 'name' => 'Xã Hoa Sơn', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10366, 'name' => 'Xã Quảng Phú Cầu', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10369, 'name' => 'Xã Trường Thịnh', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10372, 'name' => 'Xã Cao Thành', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10375, 'name' => 'Xã Liên Bạt', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10378, 'name' => 'Xã Sơn Công', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10381, 'name' => 'Xã Đồng Tiến', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10384, 'name' => 'Xã Phương Tú', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10387, 'name' => 'Xã Trung Tú', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10390, 'name' => 'Xã Đồng Tân', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10393, 'name' => 'Xã Tảo Dương Văn', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10396, 'name' => 'Xã Vạn Thái', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10399, 'name' => 'Xã Minh Đức', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10402, 'name' => 'Xã Hòa Lâm', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10405, 'name' => 'Xã Hòa Xá', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10408, 'name' => 'Xã Trầm Lộng', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10411, 'name' => 'Xã Kim Đường', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10414, 'name' => 'Xã Hòa Nam', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10417, 'name' => 'Xã Hòa Phú', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10420, 'name' => 'Xã Đội Bình', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10423, 'name' => 'Xã Đại Hùng', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10426, 'name' => 'Xã Đông Lỗ', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10429, 'name' => 'Xã Phù Lưu', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10432, 'name' => 'Xã Đại Cường', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10435, 'name' => 'Xã Lưu Hoàng', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10438, 'name' => 'Xã Hồng Quang', 'type' => 'Xã', 'district_id' => 281],
            ['id' => 10441, 'name' => 'Thị trấn Đại Nghĩa', 'type' => 'Thị trấn', 'district_id' => 282],
            ['id' => 10444, 'name' => 'Xã Đồng Tâm', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10447, 'name' => 'Xã Thượng Lâm', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10450, 'name' => 'Xã Tuy Lai', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10453, 'name' => 'Xã Phúc Lâm', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10456, 'name' => 'Xã Mỹ Thành', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10459, 'name' => 'Xã Bột Xuyên', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10462, 'name' => 'Xã An Mỹ', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10465, 'name' => 'Xã Hồng Sơn', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10468, 'name' => 'Xã Lê Thanh', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10471, 'name' => 'Xã Xuy Xá', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10474, 'name' => 'Xã Phùng Xá', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10477, 'name' => 'Xã Phù Lưu Tế', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10480, 'name' => 'Xã Đại Hưng', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10483, 'name' => 'Xã Vạn Kim', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10486, 'name' => 'Xã Đốc Tín', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10489, 'name' => 'Xã Hương Sơn', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10492, 'name' => 'Xã Hùng Tiến', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10495, 'name' => 'Xã An Tiến', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10498, 'name' => 'Xã Hợp Tiến', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10501, 'name' => 'Xã Hợp Thanh', 'type' => 'Xã', 'district_id' => 282],
            ['id' => 10504, 'name' => 'Xã An Phú', 'type' => 'Xã','district_id' =>  282]
        ]);
    }
}
